### ISSUE TITLE
GNOME 45 plans?

### ISSUE THREAD

**Issue by iadegesso** [leotaku/zen#1]
Hi,
is there any plan to make the extension GNOME 45 compliant?

Thanks,

Iade

**Comment by leotaku** [comment]
Hello! The extension should be ready for porting to Gnome 45 with minimal effort. My plan is to test a GNOME 45 version of the extension when Fedora 39 comes out in a few days, as that is what I personally use. If I find that everything works as it should, I will release a new version.

**Comment by leotaku** [comment]
Also, you can now try the GNOME 45 port of this extension by checking out the `gnome45` branch of this repository, running `make install`, restarting your GNOME session and enabling the extension. However, be aware that I have only quickly tested this port in a VM so far, so there might still be bugs.

**Comment by leotaku** [comment]
A properly tested Gnome 45 port is now available on the master branch. I will close this issue when it is released on EGO.
